---
user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
youtube:
  video_base_url: "https://www.youtube.com/watch?v="
  cache: False

yt_dlp:
  postprocessors:
    # Extract audio using ffmpeg
    - key: "FFmpegExtractAudio"
      preferredcodec: "mp3"
  paths:
    home: "./downloads"
  writeinfojson: true
